#!/bin/bash
command="/home/dietpi/yeelight-shell-scripts/yeelight-scene.sh 0 Nightlight "
#set -x
brightness="1"
COUNTER=12
	until [  $COUNTER -lt 1 ]; do
	$command $brightness
	sleep 80
	let COUNTER-=1
	let brightness+=2
done
/home/dietpi/yeelight-shell-scripts/yeelight-scene.sh 0 Off
exit 0
